<?php

namespace CuichetteLand\websiteBundle\Repository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAllEmailReceived($user)
	{
		$query = $this -> _em -> createQuery('SELECT e FROM CuichetteLandwebsiteBundle:Email e WHERE e.idDestinataire = :idDestinataire');
		$query->setParameter('idDestinataire', $user->getID());
		return $query->getResult();
	}
	
	public function deleteEmail($id)
	{
		$query = $this -> _em -> createQuery('DELETE FROM CuichetteLandwebsiteBundle:Email e WHERE e.id = :id ');
		$query->setParameter('id', $id);
		return $query->getResult();
	}
}
