# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        
    encoders:
        CuichetteLand\websiteBundle\Entity\User: plaintext
    providers:
        main:
          entity:
            class:    CuichetteLand\websiteBundle\Entity\User
            property: mail

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
        main_login:
          pattern:   ^/login$
          anonymous: true 
        main:
          pattern:   ^/
          anonymous: true
          provider: main
          form_login:
            login_path: login
            check_path: login_check
          logout:
            path:       logout
            target:     login

