cuichette_landwebsite_homepage:
    path:     /
    defaults: { _controller: CuichetteLandwebsiteBundle:homePage:index }
    
cuichette_landwebsite_testvending:
    path:     /test
    defaults: { _controller: CuichetteLandwebsiteBundle:testVending:testVending }
    
cuichette_landwebsite_panier:
    path:     /panier
    defaults: { _controller: CuichetteLandwebsiteBundle:panier:panier }
    
login:
    path: /login
    defaults:
        _controller: CuichetteLandwebsiteBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

cuichetteform:
    path:     /register
    defaults: { _controller: CuichetteLandwebsiteBundle:User:form }

cuichette_landwebsite_deleteitem:
    path:     /delete/{id}
    defaults: { _controller: CuichetteLandwebsiteBundle:delete:delete }

cuichette_landwebsite_inbox:
    path:     /inbox
    defaults: { _controller: CuichetteLandwebsiteBundle:inbox:inbox }
    
cuichette_landwebsite_newmessage:
    path:     /newmessage
    defaults: { _controller: CuichetteLandwebsiteBundle:newmessage:newmessage }
    
cuichette_landwebsite_message:
    path:     /message/{id}
    defaults: { _controller: CuichetteLandwebsiteBundle:message:message }

cuichette_landwebsite_deletemessage:
    path:     /message/delete/{id}
    defaults: { _controller: CuichetteLandwebsiteBundle:deletemail:deletemail }    

