cuichette_landwebsite_homepage:
    path:     /
    defaults: { _controller: CuichetteLandwebsiteBundle:homePage:index }

cuichette_landwebsite_categories:
    path:     /categories/{categorie}
    defaults: { _controller: CuichetteLandwebsiteBundle:categoriesPage:categories }
