cuichette_landwebsite_homepage:
    path:     /
    defaults: { _controller: CuichetteLandwebsiteBundle:homePage:index }
cuichette_landwebsite_article:
    path:     /article
    defaults: { _controller: CuichetteLandwebsiteBundle:article:article } 
