cuichette_landwebsite_homepage:
    path:     /
    defaults: { _controller: CuichetteLandwebsiteBundle:homePage:index }
    
cuichette_landwebsite_testvending:
    path:     /test
    defaults: { _controller: CuichetteLandwebsiteBundle:testVending:testVending }
